from datetime import datetime, timedelta

from sqlalchemy import select

from app.database import Base, SessionLocal, engine
from app.models import Category, Facility, Floor, KnowledgeDocument, Mall, Store, Zone
from app.phase3 import seed_phase3
from app.phase4 import seed_phase4
from app.phase5 import seed_phase5
from app.phase6 import seed_phase6
from app.phase7 import seed_phase7
from app.phase8 import seed_phase8
from app.phase9 import seed_phase9
from app.phase10 import seed_phase10
from app.phase11 import seed_phase11
from app.phase12 import seed_phase12
from app.phase13 import seed_phase13
from app.security import seed_security
from app.learning import seed_learning


PUBLIC_VERIFIED_AT = datetime(2026, 9, 29)
PUBLIC_EXPIRES_AT = PUBLIC_VERIFIED_AT + timedelta(days=90)


def _category(db, name: str) -> Category:
    row = db.scalar(select(Category).where(Category.name == name))
    if not row:
        row = Category(name=name)
        db.add(row)
        db.flush()
    return row


def _knowledge(
    db,
    *,
    title: str,
    source_name: str,
    content: str,
) -> None:
    row = db.scalar(select(KnowledgeDocument).where(KnowledgeDocument.title == title))
    if not row:
        row = KnowledgeDocument(
            title=title,
            source_type="official_public_source",
            source_name=source_name,
            content=content,
            verified=True,
            updated_at=PUBLIC_VERIFIED_AT,
            expires_at=PUBLIC_EXPIRES_AT,
        )
        db.add(row)
        return

    row.source_type = "official_public_source"
    row.source_name = source_name
    row.content = content
    row.verified = True
    row.updated_at = PUBLIC_VERIFIED_AT
    row.expires_at = PUBLIC_EXPIRES_AT


def _upsert_public_store(db, mall: Mall, payload: dict) -> None:
    categories = [_category(db, name) for name in payload.pop("category_names")]
    floor_level = payload.pop("floor_level", None)
    floor = (
        db.scalar(select(Floor).where(Floor.mall_id == mall.id, Floor.level == floor_level))
        if floor_level is not None
        else None
    )
    row = db.scalar(select(Store).where(Store.name == payload["name"]))

    if not row:
        row = Store(
            mall_id=mall.id,
            floor_id=floor.id if floor else None,
            zone_id=None,
            **payload,
        )
        db.add(row)
        db.flush()
    else:
        row.mall_id = mall.id
        row.floor_id = floor.id if floor else None
        row.zone_id = None
        for key, value in payload.items():
            setattr(row, key, value)

    row.categories = categories


def seed_core(db):
    mall = db.scalar(select(Mall).where(Mall.name == "Ikeja City Mall"))
    if not mall:
        mall = Mall(name="Ikeja City Mall", city="Ikeja, Lagos", country="Nigeria")
        db.add(mall)
        db.flush()

    ground = db.scalar(select(Floor).where(Floor.mall_id == mall.id, Floor.level == 0))
    if not ground:
        ground = Floor(mall_id=mall.id, name="Ground Floor", level=0)
        db.add(ground)
        db.flush()
    else:
        ground.name = "Ground Floor"

    top = db.scalar(select(Floor).where(Floor.mall_id == mall.id, Floor.level == 1))
    if not top:
        top = Floor(mall_id=mall.id, name="Top Floor", level=1)
        db.add(top)
        db.flush()
    else:
        top.name = "Top Floor"

    zone_migrations = {
        "DEMO-GF-A": ("ICM-GF-A", "Ground Floor Reference Zone A"),
        "DEMO-GF-B": ("ICM-GF-B", "Ground Floor Reference Zone B"),
        "DEMO-FF-A": ("ICM-TF-A", "Top Floor Reference Zone A"),
    }
    for old_code, (new_code, new_name) in zone_migrations.items():
        zone = db.scalar(select(Zone).where(Zone.code == old_code))
        existing_target = db.scalar(select(Zone).where(Zone.code == new_code))
        if zone and not existing_target:
            zone.code = new_code
            zone.name = new_name

    for store in list(db.scalars(select(Store)).all()):
        if store.data_status == "DEMO" or store.name.startswith("Demo "):
            db.delete(store)

    for facility in list(db.scalars(select(Facility)).all()):
        if facility.data_status == "DEMO" or facility.name.startswith("Demo "):
            db.delete(facility)

    for doc in list(db.scalars(select(KnowledgeDocument)).all()):
        if doc.title == "Development Data Notice" or doc.source_type == "demo":
            db.delete(doc)

    public_stores = [
        {
            "name": "Shoprite",
            "unit": None,
            "description": "Supermarket for groceries, food, drinks, household essentials, toiletries and everyday shopping.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/shoprite/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 100,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Groceries", "Household", "Everyday Essentials"],
        },
        {
            "name": "Silverbird Cinemas",
            "unit": None,
            "description": "Cinema and entertainment venue for current movie screenings at Ikeja City Mall.",
            "nearest_landmark": "Top-floor entertainment area",
            "opening_hours": "Box office reference: daily 10:00-22:00",
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall and Silverbird public information",
            "source_url": "https://newsites.ikejacitymall.com.ng/entertainment/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-SILVERBIRD",
            "floor_level": 1,
            "discovery_priority": 99,
            "verification_confidence": "HIGH",
            "location_confidence": "FLOOR_SUPPORTED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Entertainment", "Cinema"],
        },
        {
            "name": "Miniso",
            "unit": "Shop 19+20",
            "description": "Lifestyle retailer for gifts, home items, beauty accessories, stationery, toys and everyday small essentials.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Miniso Nigeria official store locator",
            "source_url": "https://www.minisonigeria.com/product_1",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-MINISO",
            "floor_level": 0,
            "discovery_priority": 98,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Lifestyle", "Gifts", "Home", "Everyday Essentials"],
        },
        {
            "name": "Samsung Experience Store",
            "unit": None,
            "description": "Samsung phones, tablets, accessories and device support at Ikeja City Mall.",
            "nearest_landmark": "Entrance 2 reference area",
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Samsung Experience Stores Nigeria",
            "source_url": "https://sesnigeria.com/store-locator/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-SAMSUNG",
            "discovery_priority": 97,
            "verification_confidence": "HIGH",
            "location_confidence": "REFERENCE_NODE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Phones", "Accessories"],
        },
        {
            "name": "iStore",
            "unit": "Shop L62",
            "description": "Apple-focused retailer for iPhone, Mac, iPad, Apple Watch, accessories and related support.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "iStore Nigeria official store locator",
            "source_url": "https://www.istore.com.ng/pages/store-locator",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-ISTORE",
            "floor_level": 0,
            "discovery_priority": 96,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Phones", "Computers", "Accessories"],
        },
        {
            "name": "Pointek",
            "unit": "Shop L28",
            "description": "Phones, computers, televisions, appliances and consumer electronics.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Pointek official store locator",
            "source_url": "https://www.pointekonline.com/ourlocations/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-POINTEK",
            "floor_level": 0,
            "discovery_priority": 95,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Phones", "Computers", "Appliances"],
        },
        {
            "name": "HealthPlus Pharmacy",
            "unit": "Shop L29",
            "description": "Pharmacy and health retailer for medicines, wellness products, personal care and everyday health needs.",
            "nearest_landmark": None,
            "opening_hours": "Mon-Sat 08:00-21:00; Sun 08:00-21:00",
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "HealthPlus official store finder",
            "source_url": "https://healthplusnigeria.com/pages/store-finder",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-HEALTHPLUS",
            "floor_level": 0,
            "discovery_priority": 94,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Pharmacy", "Health", "Personal Care"],
        },
        {
            "name": "Medplus Pharmacy",
            "unit": None,
            "description": "Pharmacy for medicines, health products, personal care and pharmacist assistance.",
            "nearest_landmark": None,
            "opening_hours": "Daily 09:00-21:00",
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Medplus official store page",
            "source_url": "https://medplusnig.com/sellers/52",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 93,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Pharmacy", "Health", "Personal Care"],
        },
        {
            "name": "Adidas",
            "unit": None,
            "description": "Sportswear, footwear and accessories retailer listed by Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/adidas/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 92,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Sports", "Fashion", "Footwear"],
        },
        {
            "name": "Nike Store Ikeja City Mall",
            "unit": None,
            "description": "Nike footwear, clothing, sportswear and accessories.",
            "nearest_landmark": None,
            "opening_hours": "Mon-Sat 10:00-20:00; Sun 12:00-20:00",
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Nike official store directory",
            "source_url": "https://www.nike.com/retail/s/nike-store-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 91,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Sports", "Fashion", "Footwear"],
        },
        {
            "name": "Sports World",
            "unit": None,
            "description": "Sports equipment, gym equipment, exercise accessories and apparel.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/sports-world/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 90,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Sports", "Fitness"],
        },
        {
            "name": "Mango",
            "unit": None,
            "description": "Women's fashion including workwear, shoes, bags, casual wear, party wear and accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/mango/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 89,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Women", "Footwear", "Accessories"],
        },
        {
            "name": "PEP",
            "unit": None,
            "description": "Value-focused clothing and everyday apparel retailer.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/pep/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 88,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Value Retail"],
        },
        {
            "name": "Ruff 'n' Tumble",
            "unit": "Shop L47",
            "description": "Children's and baby clothing, footwear and accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Current public business directory",
            "source_url": "https://www.goafricaonline.com/ng/981667-ruff-n-tumble-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-RUFF",
            "floor_level": 0,
            "discovery_priority": 87,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Kids", "Fashion", "Baby"],
        },
        {
            "name": "Mondo",
            "unit": None,
            "description": "Designer clothing, shoes and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/mondo/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 86,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Footwear", "Accessories"],
        },
        {
            "name": "TNMax Fashion",
            "unit": None,
            "description": "Fashion for adults and children, positioned around accessible branded styles.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/tnmax-fashion/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 85,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Kids"],
        },
        {
            "name": "Liquid Black",
            "unit": None,
            "description": "Men's fashion, urban clothing and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/liquid-black/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 84,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Men", "Accessories"],
        },
        {
            "name": "Grey Velvet",
            "unit": None,
            "description": "Fashion boutique carrying a mix of designer clothing and accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/grey-velvet/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 83,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Designer"],
        },
        {
            "name": "Maybrands",
            "unit": "Shop L89",
            "description": "Watches, smartwatches, accessories, handbags and gift items from multiple brands.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Maybrands official store locator",
            "source_url": "https://maybrands.co/pages/store-locator",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 82,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Watches", "Accessories", "Gifts"],
        },
        {
            "name": "Pandora",
            "unit": "Shop 40A",
            "description": "Jewellery including bracelets, charms, rings, earrings and necklaces.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Pandora Nigeria official store listing",
            "source_url": "https://www.pandorashop.ng/pages/rings",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 81,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Jewellery", "Accessories", "Gifts"],
        },
        {
            "name": "Montaigne Place",
            "unit": "Shop L33",
            "description": "Luxury skincare, cosmetics, fragrances and wellbeing products.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Montaigne Place official locator",
            "source_url": "https://montaigneplace.com/amlocator/index/ajax/?p=2",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 80,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Beauty", "Fragrance", "Skincare"],
        },
        {
            "name": "Black|Up Boutique",
            "unit": None,
            "description": "Makeup and beauty products focused on Black and mixed skin tones.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/blackup-boutique/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 79,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Beauty", "Makeup"],
        },
        {
            "name": "Studio24",
            "unit": "Shop L48",
            "description": "Photography studio and imaging services for portraits, events and photo products.",
            "nearest_landmark": "Entrance 2",
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Studio24 public company location listing",
            "source_url": "https://www.linkedin.com/company/studio24-nigeria",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-STUDIO24",
            "floor_level": 0,
            "discovery_priority": 78,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Photography", "Services"],
        },
        {
            "name": "Airtel",
            "unit": None,
            "description": "Mobile network customer service, SIM and telecom support.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/airtel/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 77,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Telecoms", "Services"],
        },
        {
            "name": "9mobile Nigeria",
            "unit": None,
            "description": "Mobile network customer service, SIM and telecom support.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/9mobile-nigeria/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 76,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Telecoms", "Services"],
        },
        {
            "name": "Ocean Basket",
            "unit": "Shop U06",
            "description": "Seafood and sushi restaurant serving fish, calamari, prawns and other meals.",
            "nearest_landmark": "1st floor",
            "opening_hours": "Mon-Sun 10:30-22:00",
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ocean Basket Nigeria official restaurant locator",
            "source_url": "https://nigeria.oceanbasket.com/our-restaurants/ocean-basket-ikeja-city-mall/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": "ICM-OCEAN-BASKET",
            "floor_level": 1,
            "discovery_priority": 75,
            "verification_confidence": "HIGH",
            "location_confidence": "EXACT_UNIT",
            "public_rating": 3.8,
            "public_review_count": 52,
            "active": True,
            "category_names": ["Restaurant", "Seafood", "Food"],
        },
        {
            "name": "KFC Ikeja City Mall",
            "unit": "Shops L80 & L81",
            "description": "Quick-service restaurant for fried chicken, meals, sides and drinks.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public navigation listing",
            "source_url": "https://www.waze.com/live-map/directions/ng/la/ikeja/kfc-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 74,
            "verification_confidence": "MEDIUM",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Fast Food", "Food"],
        },
        {
            "name": "Pizza Hut",
            "unit": None,
            "description": "Pizza, pasta, sides and desserts.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/pizza-hut/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 73,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Pizza", "Food"],
        },
        {
            "name": "Debonairs Pizza",
            "unit": None,
            "description": "Pizza restaurant for dine-in and takeaway meals.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/debonairs-pizza/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 72,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Pizza", "Food"],
        },
        {
            "name": "Spices",
            "unit": None,
            "description": "Restaurant, bakery and confectionery offering meals and baked items.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/spices/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 71,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Bakery", "Food"],
        },
        {
            "name": "Rhapsody's",
            "unit": None,
            "description": "Restaurant and bar for dining, drinks and social outings.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official entertainment page",
            "source_url": "https://newsites.ikejacitymall.com.ng/entertainment/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 70,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Bar", "Food"],
        },
        {
            "name": "Cold Stone Creamery",
            "unit": None,
            "description": "Ice cream, cakes, desserts and cold drinks.",
            "nearest_landmark": "Food Court reference",
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current Lagos business directory",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 69,
            "verification_confidence": "MEDIUM",
            "location_confidence": "AREA_REFERENCE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Dessert", "Food", "Ice Cream"],
        },
        {
            "name": "Party Perfect",
            "unit": None,
            "description": "Party supplies, celebration items, gifts and event accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/party-perfect/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 68,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Gifts", "Party", "Specialty"],
        },
        {
            "name": "Storm",
            "unit": None,
            "description": "Watches, jewellery, belts, eyewear, cufflinks, wallets and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "Ikeja City Mall official directory",
            "source_url": "https://newsites.ikejacitymall.com.ng/store/storm/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 67,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Watches", "Accessories", "Jewellery"],
        },
        {
            "name": "Casabella",
            "unit": None,
            "description": "Beauty, haircare and personal-care retail at Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_VERIFIED",
            "source_name": "HealthPlus/Casabella public locator",
            "source_url": "https://healthplusnigeria.com/pages/family-planning-services-store-locator",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 66,
            "verification_confidence": "HIGH",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Beauty", "Haircare", "Personal Care"],
        },
        {
            "name": "Vlisco Boutique",
            "unit": "Shop L102",
            "description": "Premium wax fabrics and fashion textiles.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current Lagos business directory",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 65,
            "verification_confidence": "MEDIUM",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Fabrics"],
        },
        {
            "name": "Audacious",
            "unit": None,
            "description": "Women's clothing, shoes, bags and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current Lagos business directory",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 64,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Women", "Accessories"],
        },
        {
            "name": "REDTAG",
            "unit": None,
            "description": "Value fashion and family apparel retailer.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "ICM public directory reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 63,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Family"],
        },
        {
            "name": "Celio",
            "unit": None,
            "description": "Men's fashion and casual clothing.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "ICM public directory reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 62,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Men"],
        },
        {
            "name": "Levi's",
            "unit": None,
            "description": "Denim, jeans and casual fashion.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Ikeja City Mall public blog reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/ikeja-city-mall-blog/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 61,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Denim"],
        },
        {
            "name": "Da Viva",
            "unit": None,
            "description": "African-inspired fabrics and fashion textiles.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory references",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 60,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Fabrics"],
        },
        {
            "name": "Woodin",
            "unit": None,
            "description": "African fabrics and fashion textiles.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Recent public ICM visitor references",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 59,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Fabrics"],
        },
        {
            "name": "MAC Cosmetics",
            "unit": None,
            "description": "Cosmetics, makeup products and in-store beauty services.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Recent public ICM beauty references",
            "source_url": "https://www.africabizinfo.com/NG/mac",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 58,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Beauty", "Makeup"],
        },
        {
            "name": "SLOT",
            "unit": None,
            "description": "Phones, mobile devices and electronics retail reference at Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Public ICM retail references",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 57,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Phones"],
        },
        {
            "name": "Oraimo",
            "unit": None,
            "description": "Mobile accessories, audio products, wearables and charging devices.",
            "nearest_landmark": "Entrance 2 public reference",
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public local-business reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 56,
            "verification_confidence": "MEDIUM",
            "location_confidence": "AREA_REFERENCE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Accessories"],
        },
        {
            "name": "Fouani LG / Hisense Showroom",
            "unit": None,
            "description": "Televisions, home electronics and appliances from LG/Hisense retail channels.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public local-business reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 55,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Electronics", "Appliances"],
        },
        {
            "name": "Aldo",
            "unit": None,
            "description": "Shoes, bags and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public local-business reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 54,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Footwear", "Fashion", "Accessories"],
        },
        {
            "name": "Stanbic IBTC ATM Gallery",
            "unit": None,
            "description": "ATM and banking self-service access within the mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "ICM public directory reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 53,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Banking", "ATM", "Services"],
        },
        {
            "name": "Mobos",
            "unit": None,
            "description": "Fashion boutique and clothing retailer.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Public tenant references",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 52,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion"],
        },
        {
            "name": "Chicken Republic",
            "unit": None,
            "description": "Quick-service chicken meals, rice, sides and drinks.",
            "nearest_landmark": "Food-service reference",
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Recent public ICM visitor references",
            "source_url": "https://newsites.ikejacitymall.com.ng/food-court/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 51,
            "verification_confidence": "MEDIUM",
            "location_confidence": "AREA_REFERENCE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Fast Food", "Food"],
        },
        {
            "name": "Casper & Gambini's",
            "unit": None,
            "description": "Restaurant and cafe reference for meals, coffee and social dining.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "ICM public visitor and blog references",
            "source_url": "https://newsites.ikejacitymall.com.ng/ikeja-city-mall-blog/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 50,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Cafe", "Food"],
        },
        {
            "name": "Cilantro",
            "unit": None,
            "description": "Restaurant reference for casual dining and meals.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public local-business reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/food-court/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 49,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Food"],
        },
        {
            "name": "Shawarma & Co",
            "unit": None,
            "description": "Shawarma and quick meal reference within the mall food offering.",
            "nearest_landmark": "Food Court reference",
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 48,
            "verification_confidence": "MEDIUM",
            "location_confidence": "AREA_REFERENCE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Fast Food", "Food"],
        },
        {
            "name": "Sumptuous Menu",
            "unit": None,
            "description": "Food-service reference for prepared meals within the mall.",
            "nearest_landmark": "Food Court reference",
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 47,
            "verification_confidence": "MEDIUM",
            "location_confidence": "AREA_REFERENCE",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Restaurant", "Food"],
        },
        {
            "name": "Novesa",
            "unit": None,
            "description": "Fashion retail reference within Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 46,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion"],
        },
        {
            "name": "Identity Store",
            "unit": "Shop L046",
            "description": "Fashion retail reference within Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 45,
            "verification_confidence": "MEDIUM",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion"],
        },
        {
            "name": "Pierre Cardin",
            "unit": None,
            "description": "Fashion and accessories retail reference within Ikeja City Mall.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 44,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion", "Accessories"],
        },
        {
            "name": "Watch Galleries",
            "unit": "Shop L21",
            "description": "Watches and fashion accessories.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Public ICM retail directory references",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "floor_level": 0,
            "discovery_priority": 43,
            "verification_confidence": "MEDIUM",
            "location_confidence": "EXACT_UNIT",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Watches", "Accessories"],
        },
        {
            "name": "Truworths",
            "unit": None,
            "description": "Fashion apparel retail reference.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "Current public mall-directory reference",
            "source_url": "https://www.finelib.com/cities/lagos/shopping/shopping-centres/-ikeja-city-mall",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 42,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Fashion"],
        },
        {
            "name": "Stanbic IBTC",
            "unit": None,
            "description": "Banking and financial-services reference within the mall tenant mix.",
            "nearest_landmark": None,
            "opening_hours": None,
            "data_status": "PUBLIC_REFERENCE",
            "source_name": "ICM public directory reference",
            "source_url": "https://newsites.ikejacitymall.com.ng/shops/",
            "verified_at": PUBLIC_VERIFIED_AT,
            "expires_at": PUBLIC_EXPIRES_AT,
            "map_node_code": None,
            "discovery_priority": 41,
            "verification_confidence": "MEDIUM",
            "location_confidence": "UNMAPPED",
            "public_rating": None,
            "public_review_count": None,
            "active": True,
            "category_names": ["Banking", "Services"],
        },
    ]

    for payload in public_stores:
        _upsert_public_store(db, mall, payload.copy())

    _knowledge(
        db,
        title="Enesko Data Accuracy Policy",
        source_name="Enesko",
        content=(
            "ENESKO must not invent live operational information. Current operational claims must come from "
            "fresh staff-verified records or approved integrations. Public directory facts must retain source "
            "and verification metadata, while unavailable live data must be described as unavailable."
        ),
    )
    _knowledge(
        db,
        title="Ikeja City Mall Public Overview",
        source_name="Ikeja City Mall official website",
        content=(
            "Ikeja City Mall is located in Alausa, Ikeja, Lagos. The official mall website states that the "
            "shopping centre has over 100 shops, 12 restaurants and more than 700 parking bays."
        ),
    )
    _knowledge(
        db,
        title="Ikeja City Mall Parking Information",
        source_name="Ikeja City Mall official website",
        content=(
            "Ikeja City Mall publicly states that it provides more than 700 parking bays. This is capacity "
            "information, not live availability. Live occupancy must come from a fresh ENESKO staff update "
            "or an authorized parking integration."
        ),
    )
    _knowledge(
        db,
        title="Ikeja City Mall Lost and Found",
        source_name="Ikeja City Mall official website",
        content=(
            "Ikeja City Mall publishes a Lost and Found contact through the mall management line "
            "+234 806 858 2039. ENESKO can create and track a lost-and-found case, while physical verification "
            "and item release remain with authorized mall staff."
        ),
    )
    _knowledge(
        db,
        title="Silverbird Cinemas Ikeja City Mall",
        source_name="Silverbird Cinemas official website",
        content=(
            "Silverbird Cinemas operates at Ikeja City Mall. Its published box-office hours are Monday to "
            "Sunday, 10:00 to 22:00, and its movie enquiry line is +234 902 606 7603. Current showtimes are "
            "subject to change and should come from the official cinema service."
        ),
    )

    db.commit()


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_core(db)
        for fn in (
            seed_phase3,
            seed_phase4,
            seed_phase5,
            seed_phase6,
            seed_phase7,
            seed_phase8,
            seed_phase9,
            seed_phase10,
            seed_phase11,
            seed_phase12,
            seed_phase13,
            seed_security,
            seed_learning,
        ):
            fn(db)
        print(
            "Enesko product seed complete; public customer reference data, operational foundations and security seed are ready."
        )
    finally:
        db.close()


if __name__ == "__main__":
    seed()
